### PR TITLE
changed the copyright message and also added apple store link 

### PR DESCRIPTION
**Pull request by Alok-1512**
PR for fixing issue #124

### CODE REVIEW

**Comment by Alok-1512** [comment]
Printed the year dynamically and also added the apple store logo for redirection along with the link in footer for issue #129

**Comment by samanyougarg** [comment]
Failing to compile on local.
Screenshot 2023-06-23 at 12 38 39 AM

**Comment by samanyougarg** [comment]
- [ ] Ved Vyas Foundation should be a hyperlink to https://vedvyas.org
- [ ] App store icon is too small

Screenshot 2023-06-23 at 12 40 15 AM

**Comment by Alok-1512** [comment]
will check and update again

**Comment by Alok-1512** [comment]
i have added a commit for the error and the hyperlink but couldn't check for the small icon issue as i cant run it on my machine

**Comment by Alok-1512** [comment]
run_err

**Comment by samanyougarg** [comment]
@eht-ck is picking this up in #150 PR so closing this for now.

**Pull request closed without merging**
