### PR TITLE
🚀 feat: auth screens

### PR DESCRIPTION
**Pull request by akshitarora921**
This is just the front-end part linking with supebase is pending.
use route `/login` and `/signup` to see the pages.
part of #46

### CODE REVIEW

**Comment by Gupta-Anubhav12** [comment]
Hey 
This works really great,
One more thing that can be done is to include the homepage navbar at top,
It was probably missing in designs

**Comment by akshitarora921** [comment]
@Gupta-Anubhav12, I think the homepage header is specifically removed by the designer to give clean look to the auth screens. Let's discuss with the designer and then proceed.

**Comment by Gupta-Anubhav12** [comment]
Looks good to merge

**Comment by Gupta-Anubhav12** [comment]
will have to fetch main and then we can merge

**Pull request merged**
