### PR TITLE
Sk/bug188 chapter page

### PR DESCRIPTION
**Pull request by sarthak-kumar-shailendra**
Resolving bug - 188
https://github.com/gita/gita-frontend-v2/issues/188 reported by @samanyougarg 

1. Reduced verse selection dropdown size on chapter page.
2. Resolved spacing issues of verse numbers and right side extra margin
3. Clicking on verse number directly opens the verse page

### CODE REVIEW

**Comment by samanyougarg** [comment]
Thanks for picking up this PR @sarthak-kumar-shailendra !

**Comment by samanyougarg** [comment]
`Reduced verse selection dropdown size on chapter page.`
This is fixed.

**Comment by samanyougarg** [comment]
`Resolved spacing issues of verse numbers and right side extra margin` 
There are some more issues here. When there are too many shlokas, the dropdown looks weird.

See the gap after 46:
Screenshot 2023-09-25 at 12 12 46 AM

Additionally, the dropdown is becoming too long if there are too many verses. Can we try something else for better UX? Perhaps show the first 4 rows of shlokas and then add a scrollbar?

**Comment by samanyougarg** [comment]
`Clicking on verse number directly opens the verse page`
This has been fixed and is working well thank you!

**Comment by samanyougarg** [comment]
Could you please pick up this one as well:

`Clicking outside the verse selection box should close it.`

**Comment by sarthak-kumar-shailendra** [comment]
@samanyougarg will do the required changes

**Comment by sarthak-kumar-shailendra** [comment]
Have fixed this  - "Clicking outside the verse selection box should close it."
Also, have added max height and scroll behaviour to dropdown. However, was not able to repro that gap issue after 46th verse... 
@samanyougarg can you check again and let me know the screen dimensions if it's still happening



Screenshot 2023-09-25 at 10 33 13 PM

**Comment by sarthak-kumar-shailendra** [comment]
@samanyougarg pls check this

**Comment by sarthak-kumar-shailendra** [comment]
Hare Krishna
pls review @samanyougarg

**Comment by samanyougarg** [comment]
Hare Krishna, the height of this dropdown still needs reduction.
CleanShot 2024-01-21 at 00 05 13@2x

**Comment by samanyougarg** [comment]
Other things seem good. Once we reduce the height, we can merge. Sorry for the delay here.

**Review by samanyougarg — CHANGES_REQUESTED** [review]
Please fix dropdown height.

**Comment by sarthak-kumar-shailendra** [comment]
Hare Krishna, 
I have already reduced the height of the dropdown menu to accommodate the first 4 rows as instructed before. Do you want to make it even shorter or are you asking me to reduce the height of the dropdown CTA? @samanyougarg  

Screenshot 2024-01-22 at 12 46 07 AM

**Pull request closed without merging**
