### PR TITLE
Merged ssr

### PR DESCRIPTION
**Pull request by elmeister**
### Summary by CodeRabbit

- New Feature: Added support for internationalization (i18n) with "en" and "ru" locales.
- Refactor: Updated ESLint and Prettier configurations for better code consistency and readability.
- Refactor: Simplified layout components by removing redundant wrappers and improving the structure.
- Chore: Updated `.gitignore` to include more files and directories.
- New Feature: Integrated `gqty`, a GraphQL client library, for improved API interactions.
- Refactor: Removed several unused components and pages, enhancing maintainability.
- New Feature: Introduced new HomePage component with improved structure and functionality.

### CODE REVIEW

**Comment by samanyougarg** [comment]
- [x] Many texts fetch from GQL are in English even tho the selected language is Hindi.

Verse of the day section on homepage
Screenshot 2023-08-26 at 11 00 44 PM

Chapter list on homepage
Screenshot 2023-08-26 at 11 01 21 PM

Chapter description
Screenshot 2023-08-26 at 11 01 37 PM

Verse list of chapter page
Screenshot 2023-08-26 at 11 01 52 PM

**Comment by samanyougarg** [comment]
- [x] Audio player title needs to be in hindi.

Screenshot 2023-08-26 at 11 02 36 PM

**Comment by samanyougarg** [comment]
- [x] Customization modal strings need translation.

Screenshot 2023-08-26 at 11 03 08 PM

**Comment by samanyougarg** [comment]
- [x] When language is non-English, we can hide the transliteration and word meanings.

Screenshot 2023-08-26 at 11 03 56 PM

**Comment by samanyougarg** [comment]
- [ ] Switching between pages has like 1 sec delay. Is there a way to make it instant?

https://www.loom.com/share/070b14758d624259a9c24ce4a3bf3ff3

**Comment by samanyougarg** [comment]
- [x] Search page needs translation.

Screenshot 2023-08-26 at 11 06 15 PM

**Comment by elmeister** [comment]
> Search page needs translation.

Done

>  Switching between pages has like 1 sec delay. Is there a way to make it instant?

This second is required to load verse data from DB
Please share access to DB and hasura console, so I will check what's the reason of the slow response

>  Customization modal strings need translation.

Done

>  When language is non-English, we can hide the transliteration and word meanings.

Done

>  Audio player title needs to be in hindi.

Done

>  Many texts fetch from GQL are in English even tho the selected language is Hindi.

Done

**Pull request merged**
